name: transcription_frontend_flutter
description: Una aplicación Flutter para transcripción de audio.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Librerías necesarias
  http: ^1.2.2  # Para interactuar con el backend
  file_picker: ^5.2.3  # Para seleccionar archivos

  # Esto viene por defecto para manejar Material Design
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
